# Generated by Django 2.2 on 2019-04-03 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smaczek', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smaczek.ProductType')),
            ],
        ),
    ]
